<a href="https://colab.research.google.com/github/mihao/tmp/blob/main/dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.random.randint(10, 100, (10, 5)), columns=list('ABCDE'))

In [3]:
df.set_index(['A', 'B']).reset_index().set_index(['C', 'D']).rename_axis(['blah', 'blorf'])

             A   B   E
blah blorf
22   76     40  19  57
16   76     21  55  44
52   39     61  16  78
79   45     18  65  66
15   27     96  31  53
61   39     40  88  68
47   97     16  70  78
72   70     28  47  92
36   68     16  67  51
10   47     43  18  64